# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-14.04"

  config.vm.define :server do |srv|
    srv.vm.hostname = "inserver"
    srv.vm.network "private_network", ip: "192.168.34.10", :mac => "080027538b38"
    srv.vm.provision "shell", path: "inserver.sh"
    config.ssh.forward_x11 = true
  end

  config.vm.define :router do |router|
    router.vm.hostname = "router"
    router.vm.network "private_network", ip: "192.168.34.2", :mac => "080027004471"
    router.vm.network "private_network", ip: "192.168.41.2", :mac => "080027004472"
    router.vm.provision "shell", path: "simple_router.sh"
    config.ssh.forward_x11 = true
    router.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end
  end

  config.vm.define :client do |cl|
    cl.vm.hostname = "roclient"
    cl.vm.network "private_network", ip: "192.168.41.5", :mac => "080027c11347"
    cl.vm.provision "shell", path: "client.sh"
    config.ssh.forward_x11 = true
  end

end
