#include "lib/stubs/hardware_stub.h"

#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "rte_cycles.h" // to include the next one cleanly
#include "generic/rte_cycles.h" // for rte_delay_us_callback_register

#include <klee/klee.h>


typedef uint32_t (*stub_register_read)(struct stub_device* dev, uint32_t current_value);
typedef uint32_t (*stub_register_write)(struct stub_device* dev, uint32_t current_value, uint32_t new_value);

struct stub_register {
	bool present; // to distinguish registers we model from others
	uint32_t initial_value;
	bool readable;
	uint32_t writable_mask; // 0 = readonly, 1 = writeable
	stub_register_read read; // possibly NULL
	stub_register_write write; // possibly NULL
};

static struct stub_register REGISTERS[0x20000]; // index == address

// Incremented at each delay; in nanoseconds.
static uint64_t TIME;


// Helper bit macros
#define GET_BIT(n, k) (((n) >> (k)) & 1)
#define SET_BIT(n, k, v) if (v == 0) { n = (n & ~(1 << (k))); } else { n = (n | (1 << (k))); }

// Helper register macros
#define DEV_MEM(dev, offset, type) *((type*) (dev->mem_shadow + (offset)))
#define DEV_REG(dev, offset) DEV_MEM(dev, offset, uint32_t)


// Unless otherwise stated, all citations here refer to
// https://www.intel.com/content/dam/www/public/us/en/documents/datasheets/82599-10-gbe-controller-datasheet.pdf


static void
stub_delay_us(unsigned int us)
{
klee_print_expr("DELAY", us);
	TIME += us * 1000 ; // TIME is in ns
}


static void
stub_device_reset(struct stub_device* dev)
{
	for (int n = 0; n < sizeof(REGISTERS)/sizeof(REGISTERS[0]); n++) {
		DEV_REG(dev, n) = REGISTERS[n].initial_value;
	}

	dev->current_mdi_address = -1;
}


// RW1C means a register can be read, and bits can be cleared by writing 1
static uint32_t
stub_register_rw1c_write(struct stub_device* dev, uint32_t current_value, uint32_t new_value)
{
	for (int n = 0; n <= 31; n++) {
		if (GET_BIT(new_value, n) == 1) {
			SET_BIT(new_value, n, 0);
		} else {
			// Cannot flip a bit from 1 to 0
			klee_assert(current_value == 0);
		}
	}
	return 0;
}


static uint32_t
stub_register_i2cctl_write(struct stub_device* dev, uint32_t current_value, uint32_t new_value)
{
	// Citations here are from https://www.nxp.com/docs/en/user-guide/UM10204.pdf

	// Table 10, "Characteristics of the SDA and SCL bus lines for Standard [...] I2C devices"
	// NOTE: START setup and STOP setup are both >= TIME_LOW so we just ignore them
	const int TIME_START_HOLD = 4000; // SDA must keep its value for this long after a start
	const int TIME_BETWEEN_STOP_START = 4700;
	const int TIME_LOW = 4700; // minimum time for the clock to be in LOW
	const int TIME_HIGH = 4000; // minimum time for the clock to be in HIGH

	// I2C States
	// -1 is default
	const int I2C_STARTING = 0;
	const int I2C_STARTED = 1;
	const int I2C_STRETCHED = 2;
	const int I2C_STOPPED = 3;
	const int I2C_READING = 4;
	const int I2C_WRITING = 5;

	uint8_t scl_old = (current_value >> 1) & 1;
	uint8_t sda_old = (current_value >> 3) & 1;

	uint8_t scl_new = (new_value >> 1) & 1;
	uint8_t sda_new = (new_value >> 3) & 1;

	// Clone the out bits to the in bits - clock (1/0) and data (3/2)
	// NOTE: We model the out bits as writable because the driver has to write to them;
	//       otherwise, it would need to read I2CCTL every time before writing, which would be inefficient;
	//       so instead it just writes whatever to them and the value is ignored.
	SET_BIT(new_value, 0, GET_BIT(new_value, 1));
	SET_BIT(new_value, 2, GET_BIT(new_value, 3));

	if (scl_old != scl_new) {
		if (scl_new == 0) {
			klee_assert(TIME - dev->i2c_clock_time >= TIME_HIGH);
		} else {
			klee_assert(TIME - dev->i2c_clock_time >= TIME_LOW);
		}

		dev->i2c_clock_time = TIME;
	}

	if (dev->i2c_state == -1 || dev->i2c_state == I2C_STOPPED) {
		// "A HIGH to LOW transition on the SDA line while SCL is HIGH defines a START condition"
		if (sda_old == 1 && sda_new == 0 && scl_old == 1 && scl_new == 1) {
			if (dev->i2c_state == I2C_STOPPED) {
				klee_assert(dev->i2c_stop_time + TIME_BETWEEN_STOP_START <= TIME);
			}

			dev->i2c_state = I2C_STARTING;
			dev->i2c_start_time = TIME;
		}

		return new_value;
	}

	if (dev->i2c_state == I2C_STARTING) {
		if (sda_old != sda_new) {
			klee_assert(TIME - dev->i2c_start_time >= TIME_START_HOLD);

			dev->i2c_state = I2C_STARTED;
		}

		// Fall through
	}

	if (dev->i2c_state == I2C_STARTED) {
		// "Clock stretching pauses a transaction by holding the SCL line LOW.
		//  The transaction cannot continue until the line is released HIGH again."
		//TODO if (???) {
		//	dev->i2c_state = I2C_STRETCHED;
		//}

		// "A data transfer is always terminated by a STOP condition generated by the master."
		// (there is also a "repeated START" but we don't have multiple slaves)
		// "A LOW to HIGH transition on the SDA line while SCL is HIGH defines a STOP condition"
		if (sda_old == 0 && sda_new == 1 && scl_old == 1 && scl_new == 1) {
			// "A START condition immediately followed by a STOP condition (void message) is an illegal format."
			klee_assert(dev->i2c_counter > 0);

			// also, let's make sure the message didn't stop at some random place
			klee_assert(dev->i2c_counter % 9 == 0);

			dev->i2c_state = I2C_STOPPED;
			dev->i2c_counter = 0;
			dev->i2c_address = 0;
			dev->i2c_stop_time = TIME;

			return new_value;
		}

		// "After the START condition, a slave address is sent.
		//  This address is seven bits long followed by an eight bit which is a data direction bit (R/W) -
		//  a 'zero' indicates a transmission (WRITE), a 'one' indicates a request for data (READ)

		if (scl_old == 0 && scl_new == 1) {
			// Rising edge!
			// Now we have the value in sda_new

			if (dev->i2c_counter % 9 < 8) {
				// Part of the address or the RW bit - read a bit
				dev->i2c_address = dev->i2c_address << 1;
				dev->i2c_address = dev->i2c_address | sda_new;
			} else if (dev->i2c_counter == 8) {
				// "Each byte is followed by an acknowledgement bit"
				// "The Acknowledge signal is defined as follows: the transmitter releases the SDA line
				//  during the acknowledge clock pulse so the receiver can pull the SDA line LOW
				//  and it remains stable LOW suring the HIGH period of this clock pulse."
				SET_BIT(new_value, 2, 0); // bit 2 is "data in"

				// Set the state since we got an ACK
				dev->i2c_state = (dev->i2c_address & 1) == 0 ? I2C_READING : I2C_WRITING;
				// Also remove the RW bit from the address
				dev->i2c_address = dev->i2c_address >> 1;

				// "The 10-bit slave address is formed from the first two bytes following a START condition"
				// "The first seven bits of the first byte are the combination 1111 0XX"
				// "Although there are eight possible combinations of the reserved address bits 1111 xxx,
				//  only the four combinations 1111 0XX are used for 10-bit addressing.
				//  The remaining four combinations 1111 1XX are reserved for future I2C-bus enhancements."
				// we don't support 10-bit mode, nor the reserved stuff
				klee_assert(dev->i2c_address >> 3 != 0b1111);
			}

			dev->i2c_counter++;
		}

		return new_value;
	}

	if (dev->i2c_state == I2C_READING || dev->i2c_state == I2C_WRITING) {
		if (scl_old == 0 && scl_new == 1) {
			// Rising edge!
			// Now we have the value in sda_new

			klee_abort();

			dev->i2c_counter++;
		}

		return new_value;
	}

	if (dev->i2c_state == I2C_STRETCHED) {
		//TODO if (???) {
		//	dev->i2c_state = I2C_STARTED;
		//}

		return new_value;
	}

	return new_value; // TODO
}


static uint32_t
stub_register_ctrl_write(struct stub_device* dev, uint32_t current_value, uint32_t new_value)
{
	// Bit 2 is cleared once no master requests are pending, which we don't emulate anyway
	SET_BIT(new_value, 2, 0);

	// Bit 3 is self-clearing
	if (GET_BIT(new_value, 3) == 1) {
		SET_BIT(new_value, 3, 0);
		// TODO reset MAC, PCS and autonegotiation
	}

	// Bit 26 is self-clearing
	if (GET_BIT(new_value, 26) == 1) {
		SET_BIT(new_value, 26, 0);
		stub_device_reset(dev);
	}

	return new_value;
}


static uint32_t
stub_register_eerd_write(struct stub_device* dev, uint32_t current_value, uint32_t new_value)
{
	// Cannot set the done bit to 1, only clear it
	klee_assert(!(GET_BIT(current_value, 1) == 0 && GET_BIT(new_value, 1) == 1));
	// Same with the data
	for (int n = 16; n <= 31; n++) {
		klee_assert(!(GET_BIT(current_value, n) == 0 && GET_BIT(new_value, n) == 1));
	}

	bool read = GET_BIT(new_value, 0);
	uint16_t addr = (new_value >> 2) & 0b11111111111111;
klee_print_expr("EEPROM READ", read);
klee_print_expr("addr", addr);

	// Clear read bit
	SET_BIT(new_value, 0, 0);
	// Clear data bits
	for (int n = 16; n <= 31; n++) {
		SET_BIT(new_value, n, 0);
	}

	// Checksum word - sum of all words from 0x00 to 0x3F (including words pointed to if any) must be 0xBABA
	if (addr == 0x3F) {
		new_value |= (0xBABA << 16);
	}

	// Mark read as done
	// TODO some timeouts?
	SET_BIT(new_value, 1, 1);

	return new_value;
}


static uint32_t
stub_register_msca_write(struct stub_device* dev, uint32_t current_value, uint32_t new_value)
{
	// page 135
	// MDIO Direct Access

	// Bit 30 is "MDI Command", 1 means perform operation
	if (GET_BIT(new_value, 30) == 0) {
		// bit cleared, nothing to do
		return new_value;
	}

	// Bit 30 says there is a command; start by clearing it, since we execute everything instantaneously
	SET_BIT(new_value, 30, 0);

	// "start code [00b] that identifies clause 45 format"
	if (((new_value >> 28) & 0b11) == 0b00) {
		int opcode = (new_value >> 26) & 0b11;

		if (opcode == 0b00) { // address operation
			klee_assert(dev->current_mdi_address == -1);
			dev->current_mdi_address = new_value & 0xFF;
klee_print_expr("dev",*dev);
klee_print_expr("ADDR PHY", dev->current_mdi_address);
		} else if (opcode == 0b11) { // read operation
klee_print_expr("dev", *dev);
klee_print_expr("READ PHY", dev->current_mdi_address);

			klee_assert(dev->current_mdi_address != -1);

			int phy_addr = (new_value >> 21) & 0b11111;
			klee_print_expr("phy addr", phy_addr);
			dev->current_mdi_address = -1;

			uint32_t result = 0; // return value is always 0...
			DEV_REG(dev, 0x04260) = result; // register MSRWD holds the result
		} else {
			klee_abort(); // unsupported
		}
	} else {
		// clause 22 format
		klee_abort(); // unsupported
	}

	return new_value;
}


static uint32_t
stub_register_txdctl_write(struct stub_device* dev, uint32_t current_value, uint32_t new_value)
{
	// Bit 26 is self-clearing
	if (GET_BIT(new_value, 26) == 1) {
		SET_BIT(new_value, 26, 0);
	}

	return new_value;
}


static uint32_t
stub_register_swsm_read(struct stub_device* dev, uint32_t current_value)
{
	SET_BIT(current_value, 1, 1); // LSB is the semaphore bit - always set after a read
	return current_value;
}

static uint32_t
stub_register_swsm_write(struct stub_device* dev, uint32_t current_value, uint32_t new_value)
{
	// Cannot set the semaphore bit to 1, only clear it
	klee_assert(!(GET_BIT(current_value, 0) == 0 && GET_BIT(new_value, 0) == 1));

	// Can only take the software semaphore bit if the semaphore is taken
	if (GET_BIT(current_value, 1) == 0 && GET_BIT(new_value, 1) == 1) {
		klee_assert(GET_BIT(current_value, 0) == 1);
	}

	return new_value; // OK, we only check
}


static uint32_t
stub_register_swfwsync_write(struct stub_device* dev, uint32_t current_value, uint32_t new_value)
{
	// Cannot write to this register unless the software semaphore bit of SWSM is taken
	klee_assert(GET_BIT(DEV_REG(dev, 0x10140), 1) == 1);

	// Cannot write 1 to a bit in this register if the firmware set the corresponding bit
	for (int n = 0; n < 5; n++) {
		klee_assert(GET_BIT(new_value, n) + GET_BIT(current_value, n + 5) <= 1);
	}

	return new_value; // OK, we only check
}


static void
stub_registers_init(void)
{
	#define REG(addr, val, mask) do {                      \
				struct stub_register reg = {   \
					.present = true,       \
					.initial_value = val,  \
					.readable = true,      \
					.writable_mask = mask, \
					.read = NULL,          \
					.write = NULL          \
				};                             \
				REGISTERS[addr] = reg;         \
			} while(0);

	// page 543
	// Device Control Register — CTRL (0x00000 / 0x00004; RW)
	// NOTE: "CTRL is also mapped to address 0x00004 to maintain compatibility with previous devices."

	// 0-1: Reserved (0)
	// 2: PCIe Master Disable (0 - not disabled)
	// 3: Link Reset (0 - not reset; self-clearing)
	// 4-25: Reserved (0)
	// 26: Device Reset (0 - not reset; self-clearing)
	// 27-31: Reserved (0)
	REG(0x00000, 0b00000000000000000000000000000000,
		     0b00000100000000000000000000001100);
	REGISTERS[0x00000].write = stub_register_ctrl_write;
	// TODO should we do the 0x00004 mapping?


	// page 544
	// Device Status Register — STATUS (0x00008; RO)

	// 0-1: Reserved (00)
	// 2-3: Lan ID (00 - Lan 0 / 01 - Lan 1)
	// 4-6: Reserved (00)
	// 7: Linkup Status Indication (0 - ???)
	// 8-9: Reserved (00)
	// 10-17: Num VFs (0 - no VFs; note: "Bit 17 is always 0b")
	// 18: IO Active (0 - not active; note: "reflects the value of the VF Enable (VFE) bit in the IOV Control/Status register")
	// 19: Status (0 - not issuing any master requests)
	// 20-31: Reserved (0x00)
	REG(0x00008, 0b00000000000000000000000000000000,
		     0b00000000000000000000000000000000);


	// page 549
	// I2C Control — I2CCTL (0x00028; RW)

	// 0: I2C Clock In (0 - default; read-only)
	// 1: I2C Clock Out (0 - default)
	// 2: I2C Data In (0 - default; read-only)
	// 3: I2C Data Out (0 - default)
	// 4-31: Reserved
	REG(0x00028, 0b00000000000000000000000000001111, // in a pull-up system like I2C, 1 is the default
		     0b00000000000000000000000000001111); // NOTE: 0 and 2 are RW, see i2cctl_write for an explanation
	REGISTERS[0x00028].write = stub_register_i2cctl_write;


	// page 572
	// Extended Interrupt Cause Register- EICR (0x00800; RW1C)

	// 0-15: Receive/Transmit Queue Interrupts (0x0 - not enabled)
	// 16: Flow director (0 - no)
	// 17: Missed packet (0 - no)
	// 18 - PCI timeout (0 - no)
	// 19: VF to PF MailBox (0 - no)
	// 20: Link Status Change (0 - no) TODO use this
	// 21: TX LinkSec counter reached threshold requiring key exchange (0 - no)
	// 22: Manageability event detected (0 - no)
	// 23: Reserved (0)
	// 24: General Purpose Interrupt on SDP0 (0 - no)
	// 25: General Purpose Interrupt on SDP1 (0 - no)
	// 26: General Purpose Interrupt on SDP2 (0 - no)
	// 27: General Purpose Interrupt on SDP3 (0 - no)
	// 28: Unrecoverable ECC Error (0 - no) TODO try this, software must reset if this is set
	// 29: Reserved (0)
	// 30: TCP Timer Expired (0 - no)
	// 31: Other interrupt - from EICR (0 - no)
	REG(0x00800, 0b00000000000000000000000000000000,
		     0b00000000000000000000000000000001);
	REGISTERS[0x00800].write = stub_register_rw1c_write;

	// page 574
	// Extended Interrupt Mask Clear Register- EIMC (0x00888; WO)
	// TODO do we model interrupts?

	// 0-30: Interrupt Mask (0 - don't care, write-only register)
	// 31: Reserved
	REG(0x00888, 0b00000000000000000000000000000000,
		     0b01111111111111111111111111111111);
	REGISTERS[0x00888].readable = false;


	// page 597
	// Receive Descriptor Control — RXDCTL[n] (0x01028 + 0x40*n, n=0...63 and 0x0D028 + 0x40*(n-64), n=64...127; RW)
	for (int n = 0; n <= 127; n++) {
		int addr = n < 64 ? (0x01028 + 0x40*n) : (0x0D028 + 0x40*(n-64));

		// 0-13: Reserved (0)
		// 14: Reserved, but readable/writeable for compatibility
		// 15: Reserved (0)
		// 16-22: Reserved, but readable/writeable for compatibility
		// 23-24: Reserved (00)
		// 25: Receive Queue Enable (0 - not enabled)
		// 26: Reserved, but readable/writeable for compatibility
		// 27-29: Reserved
		// 30: VLAN Mode Enable
		// 31: Reserved
		REG(addr, 0b00000000000000000000000000000000,
			  0b00000110011111110100000000000000);
	}


	// page 600
	// Receive Control Register — RXCTRL (0x03000; RW)

	// 0: Receive Enable (0 - not yet enabled)
	// 1-31: Reserved
	REG(0x03000, 0b00000000000000000000000000000000,
		     0b00000000000000000000000000000001);


	// page 668
	// MDI Single Command and Address — MSCA (0x0425C; RW)

	// 0-15: MDI Address (0x0000 - default)
	// 16-20: DeviceType/Register Address (0x0 - default)
	// 21-25: PHY Address (0x0 - default)
	// 26-27: OP Code (00 - default; all 4 combinations are valid)
	// 28-29: ST Code (0 - New protocol, default; only 00 and 01 are valid)
	// 30: MDI Command (0 - ready)
	// 31: Reserved
	REG(0x0425C, 0b00000000000000000000000000000000,
		     0b01011111111111111111111111111111); // bit 29 is read-only since it cannot be 1
	REGISTERS[0x0425C].write = stub_register_msca_write;


	// page 669
	// MDI Single Read and Write Data — MSRWD (0x04260; RW)

	// 0-15: MDI Write Data (0 - default)
	// 16-31: MDI Read Data (0 - default; read-only)
	REG(0x04260, 0b00000000000000000000000000000000,
		     0b00000000000000001111111111111111);


	// page 606
	// Transmit Descriptor Control — TXDCTL[n] (0x06028+0x40*n, n=0...127; RW)
	for (int n = 0; n <= 127; n++) {
		// 0-6: Prefetch Threshold (0x0 - zero)
		// 7: Reserved (0)
		// 8-14: Host Threshold (0x0 - zero) TODO check that if PTHRESH is used HTHRESH is >0
		// 15: Reserved (0)
		// 16-22: Write-Back Threshold (0x0 - zero)
		// 23-24: Reserved (0)
		// 25: Transmit Queue Enable (0 - not enabled)
		// 26 - Transmit Software Flush (0 - not enabled; note: "This bit is self cleared by hardware")
		// 27-31: Reserved (0)
		REG(0x06028 + 0x40*n, 0b00000000000000000000000000000000,
				      0b00000110000000000000000000000000);
		REGISTERS[0x06028 + 0x40*n].write = stub_register_txdctl_write;
	}


	// page 552
	// EEPROM/Flash Control Register — EEC (0x10010; RW)

	// 0: Clock input (0 - not enabled)
	// 1: Chip select (0 - not enabled)
	// 2: Data input (0 - not enabled)
	// 3: Data output (X - don't care)
	// 4-5: Flash Write Enable Control (11 - not allowed)
	// 6: Request EEPROM Access (0 - not enabled)
	// 7: Grant EEPROM Access (0 - not enabled)
	// 8: EEPROM Present (1 - present, correct signature)
	// 9: EEPROM Auto-Read Done (1 - done, since we fake hardware...)
	// 10: Reserved (1 - Reserved)
	// 11-14: EEPROM Size (0100 - Default)
	// 15: PCIe Analog Done (0 - not done)
	// 16: PCIe Core Done (0 - not done)
	// 17: PCIe General Done (0 - not done)
	// 18: PCIe Function Done (0 - not done)
	// 19: Core Done (0 - not done)
	// 20: Core CSR Done (0 - not done)
	// 21: MAC Done (0 - not done)
	// 22-31: Reserved (0x0)
	REG(0x10010, 0b00000000000000000001011100110000,
		     0b00000000000000000000000000000000);


	// page 554
	// EEPROM Read Register — EERD (0x10014; RW)
	// "This register is used by software to cause the 82599 to read individual words in the EEPROM."

	// 0: Start (0 - not started)
	// 1: Done (0 - no read perfomed yet)
	// 2-15: Address (0x0 - no read performed yet)
	// 16-31: Data (0x0 - no read performed yet)
	REG(0x10014, 0b00000000000000000000000000000000,
		     0b11111111111111111111111111111111);
	REGISTERS[0x10014].write = stub_register_eerd_write;

	// page 567
	// Software Semaphore Register — SWSM (0x10140; RW)
	// "This register is shared for both LAN ports."
	// NOTE: Bit 0 is automatically set to 1 by the hardware after a read
	// NOTE: See SW_FW_SYNC dance described below

	// 0: Semaphore (0 - not accessing)
	// 1: Software Semaphore (0 - not set)
	// 2-31: Reserved (0x0)
	REG(0x10140, 0b00000000000000000000000000000000,
		     0b00000000000000000000000000000011);
	REGISTERS[0x10140].read = stub_register_swsm_read;
	REGISTERS[0x10140].write = stub_register_swsm_write;


	// pages 567-568
	// Firmware Semaphore Register — FWSM (0x10148; RW)
	// "This register should be written only by the manageability firmware.
	//  The device driver should only read this register."

	// 0: Firmware semaphore (0 - not accessing)
	// 1-3: Firmware mode (000 - none, manageability off)
	// 4-5: Reserved (00)
	// 6: EEPROM Reloaded Indication (1 - has been reloaded)
	// 7-14: Reserved (0x0)
	// 15: Firmware Valid Bit (1 - ready, boot has finished) TODO make it 0
	// 16-18: Reset Counter (000 - not reset)
	// 19-24: External Error Indication (0x00 - No error)
	// 25: PCIe Configuration Error Indication (0 - no error)
	// 26: PHY/SERDES0 Configuration Error Indication (0 - no error, LAN0 is fine)
	// 27: PHY/SERDES1 Configuration Error Indication (0 - no error, LAN1 is fine)
	// 28-31: Reserved (0000)
	REG(0x10148, 0b00000000000000001000000001000000,
		     0b00000000000000000000000000000000);


	// page 565
	// Function Active and Power State to Manageability — FACTPS (0x10150; RO)

	// 0-1: Power state indication of function 0 (00 - DR)
	// 2: Lan 0 Enable (1 - enabled)
	// 3: Function 0 Auxiliary Power PM Enable (0 - ???)
	// 4-5: Reserved (00)
	// 6-7: Power state indication of function 1 (00 - disabled)
	// 8: Lan 1 Enable (0 - disabled)
	// 9: Function 1 Auxiliary Power PM Enable (0 - disabled)
	// 10-28: Reserved (0x0)
	// 29: Manageability Clock Gated (0 - not gated)
	// 30: LAN Function Sel (0 - not inverted) TODO enable
	// 31: PM State Changed (0 - not changed)
	REG(0x10150, 0b00000000000000000000000000000100,
		     0b00000000000000000000000000000000);


	// page 569
	// Software–Firmware Synchronization — SW_FW_SYNC (0x10160; RW)
	// "This register is shared for both LAN ports."
	// NOTE: See 0x10140 and 0x10148
	// NOTE: Also known as "General Software Semaphore Register", or GSSR
	// NOTE: See Section 10.5.4 "Software and Firmware Synchronization"
	//       The SW_FW_SYNC dance's happy path is:
	//       - Software locks SWSM.SMBI by reading and getting 0 (hardware automatically sets it to 1)
	//       - Software locks SWSM.SWESMBI by writing 1 then reading 1
	//       - Software sets/clears the SW_FW_SYNC access bits it wants to by writing 1/0
	//         (locks only if firmware hasn't sets the counterpart bits)
	//       - Software clears SWSM.SWESMBI by writing 0
	//       - Software clears SWSM.SMBI by writing 0

	// 0: EEPROM software access
	// 1: PHY 0 software access
	// 2: PHY 1 software access
	// 3: Shared CSRs software access
	// 4: Flash software access
	// 5: EEPROM firmware access
	// 6: PHY 0 firmware access
	// 7: PHY 1 firmware access
	// 8: Shared CSRs firmware access
	// 9: Flash firmware access (note: "Currently the FW does not access the FLASH")
	// 10-31: Reserved
	REG(0x10160, 0b00000000000000000000000000000000,
		     0b00000000000000000000000000011111);
	REGISTERS[0x10160].write = stub_register_swfwsync_write;
}

static void
stub_device_init(struct stub_device* dev)
{
	// "Fake" memory, intercepted
	dev->mem = malloc(dev->mem_len);
	klee_intercept_reads(dev->mem, "stub_hardware_read");
	klee_intercept_writes(dev->mem, "stub_hardware_write");

	// Real backing store
	dev->mem_shadow = malloc(dev->mem_len);
	memset(dev->mem_shadow, 0, dev->mem_len);

	for (int n = 0; n < sizeof(REGISTERS)/sizeof(REGISTERS[0]); n++) {
		if (REGISTERS[n].present) {
			DEV_REG(dev, n) = REGISTERS[n].initial_value;
		}
	}
}

static struct stub_device*
stub_device_get(uint64_t addr)
{
	for (int n = 0; n < sizeof(DEVICES)/sizeof(DEVICES[0]); n++) {
		if (addr == (uint64_t) DEVICES[n].mem) {
			return &DEVICES[n];
		}
	}

	klee_abort();
}

uint64_t
stub_hardware_read(uint64_t addr, unsigned offset, unsigned size)
{
klee_print_expr("READ", addr);
klee_print_expr("off", offset);
klee_print_expr("size", size);

	struct stub_device* dev = stub_device_get(addr);

	if (size == 1) {
		return DEV_MEM(dev, offset, uint8_t);
	}
	if (size == 2) {
		return DEV_MEM(dev, offset, uint16_t);
	}
	if (size == 4) {
		uint32_t current_value = DEV_REG(dev, offset);

		struct stub_register reg = REGISTERS[offset];
		klee_assert(reg.present);
		klee_assert(reg.readable);

		if (reg.read != NULL) {
			DEV_REG(dev, offset) = reg.read(dev, current_value);
		}

		return current_value;
	}
	if (size == 8) {
		return DEV_MEM(dev, offset, uint64_t);
	}

	klee_abort();
}

void
stub_hardware_write(uint64_t addr, unsigned offset, unsigned size, uint64_t value)
{
klee_print_expr("WRITE", addr);
klee_print_expr("off", offset);
klee_print_expr("size", size);
klee_print_expr("value", value);

	struct stub_device* dev = stub_device_get(addr);

	if (size == 1) {
		DEV_MEM(dev, offset, uint8_t) = (uint8_t) value;
	} else if (size == 2) {
		DEV_MEM(dev, offset, uint16_t) = (uint16_t) value;
	} else if (size == 4) {
		struct stub_register reg = REGISTERS[offset];
		klee_assert(reg.present);

		uint32_t current_value = DEV_REG(dev, offset);
		uint32_t new_value = (uint32_t) value;
		uint32_t changed = current_value ^ new_value;

		if ((changed & ~reg.writable_mask) != 0) {
			klee_print_expr("old", current_value);
			klee_print_expr("changed", changed);
			klee_abort();
		}

		if (reg.write != NULL) {
			new_value = reg.write(dev, current_value, new_value);
		}

		DEV_REG(dev, offset) = new_value;
	} else if (size == 8) {
		DEV_MEM(dev, offset, uint64_t) = (uint64_t) value;
	} else {
		klee_abort();
	}
}


__attribute__((constructor(101))) // Low prio, must execute before other stuff
static void
stub_hardware_init(void)
{
	// Helper method declarations
	char* stub_pci_name(int index);

	// Register models initializations
	stub_registers_init();

	// Device initialization
	for (int n = 0; n < sizeof(DEVICES)/sizeof(DEVICES[0]); n++) {
		struct stub_device stub_dev = {
			.name = stub_pci_name(n),
			.mem = NULL,
			.mem_len = 1 << 20, // 2^20 bytes
			.mem_shadow = NULL,
			.current_mdi_address = -1,
			.i2c_state = -1,
			.i2c_counter = 0,
			.i2c_address = 0,
			.i2c_start_time = 0,
			.i2c_clock_time = 0,
			.i2c_stop_time = 0
		};
		stub_device_init(&stub_dev);
		DEVICES[n] = stub_dev;

	}

	// DPDK "delay" method override
	rte_delay_us_callback_register(stub_delay_us);
}

// Helper methods - not part of the stubs

char*
stub_pci_name(int index)
{
	klee_assert(index >= 0 && index < 10); // simpler

	char buffer[1024];
	snprintf(buffer, sizeof(buffer), "0000:00:00.%d", index);
	return strdup(buffer);
}
