# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-14.04"

  config.vm.define :server do |srv|
    srv.vm.hostname = "nf-serv"
    srv.vm.network "private_network", ip: "192.168.35.10", :mac => "080027538b38"
    srv.vm.provision "shell", path: "server.sh"
    config.ssh.forward_x11 = true
  end

  config.vm.define :nat do |nat|
    nat.vm.hostname = "nf-nat"
    nat.vm.network "private_network", ip: "192.168.35.2", :mac => "080027004471"
    nat.vm.network "private_network", ip: "192.168.42.2", :mac => "080027004472"
    nat.vm.provision "shell", path: "nf-nat.sh"
    config.ssh.forward_x11 = true
    nat.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end
  end

  config.vm.define :client do |cl|
    cl.vm.hostname = "nf-clnt"
    cl.vm.network "private_network", ip: "192.168.42.5", :mac => "080027c11347"
    cl.vm.provision "shell", path: "client.sh"
    config.ssh.forward_x11 = true
  end

end
